version: "3.1"

services:
  pokemon:
    container_name: pokemon
    image: pokemon/pokemon
    restart: always
    build: .
    ports:
      - "9001:9001"
    links:
      - db
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./posData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= POS
    ports:
      - 27017:27017